#This command is run before all the jobs
before_script:
  - npm install
  - npm install mocha -g --save
  - npm install source-map-support -g --save
  - npm install typescript -g --save
  - npm install ts-node -g --save

stages:
  - compile-and-test-stage

variables:
  MONGODB_VERSION: "4.2"

compile-and-test-stage:
  stage: compile-and-test-stage
  image: node:12.18.2-slim
  services:
    - mongo:$MONGODB_VERSION
  script:
    - npm run build
    - npm run testDot