#This command is run before all the jobs
before_script:
  - npm install
  - npm install mocha -g --save
  - npm install source-map-support -g --save
  - npm install typescript -g --save
  - npm install ts-node -g --save

stages:
  - build
  #- test

services:
  - mongo:$MONGODB_VERSION

cache:
  paths:
    - node_modules/

variables:
  MONGODB_VERSION: "4.2"

install_dependencies:
  stage: build
  image: node:12.18.2-slim
  script:
    - npm run build
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

#testing_testing:
#  stage: test
#  dependencies:
#    - npm
#  script:
#    - npm run testDot