variables:
  MONGODB_VERSION: "4.2"
  NODEJS_VERSION: "12.18.2-slim"
  #CI_AWS_ECS_CLUSTER: wp-ms-surveys-cluster
  #CI_AWS_ECS_SERVICE: wp-ms-surveys-survey-service
  #CI_AWS_ECS_TASK_DEFINITION: wp-ms-surveys-survey-task
  MONGO_URI: mongodb://mongo:27017/wp-ms-surveys
  PORT_SURVEY_PM2: 8090
  PORT_SURVEY_MOCHA: 8080
  PORT_OPINION_PM2: 8081
  PORT_OPINION_MOCHA: 8091
  FOREIGN_SERVICE_OPINION: http://localhost:$PORT_SURVEY_PM2/opinion
  FOREIGN_SERVICE_SURVEY: http://localhost:$PORT_OPINION_PM2/survey
  DIST_PATH_SURVEY: dist/Survey/Test
  DIST_PATH_OPINION: dist/Opinion/Test
  NODE_ENV: test

image: node:$NODEJS_VERSION

#This command is run before all the jobs
before_script:
  - npm install
  - npm install mocha -g --save
  - npm install source-map-support -g --save
  - npm install typescript -g --save
  - npm install ts-node -g --save
  - npm install pm2 -g --save

#include:
#  - template: AWS/Deploy-ECS.gitlab-ci.yml

stages:
  - build
  - test

services:
  - mongo:$MONGODB_VERSION

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm run build
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/
      - src/
      - dist/

testing_survey:
  stage: test
  services:
    - mongo:latest
  dependencies:
    - build
  script:
    - pm2 start dist/Opinion/index.js --name "opinion" --no-daemon --source-map-support -- --MONGO_URI "$MONGO_URI" --FOREIGN_SERVICE_SURVEY "$FOREIGN_SERVICE_SURVEY" --PORT "$PORT_SURVEY_PM2" --ENVIRONMENT "test"
    - mocha --MONGO_URI=$MONGO_URI --FOREIGN_SERVICE_SURVEY=$FOREIGN_SERVICE_SURVEY --PORT=$PORT_OPINION_MOCHA --ENVIRONMENT=test $DIST_PATH_OPINION

testing_opinion:
  stage: test
  services:
    - mongo:latest
  dependencies:
    - build
  script:
    - pm2 start dist/Survey/index.js --name "survey" --no-daemon --source-map-support -- --MONGO_URI "$MONGO_URI" --FOREIGN_SERVICE_OPINION "$FOREIGN_SERVICE_OPINION" --PORT "$PORT_OPINION_PM2" --ENVIRONMENT "test"
    - mocha --MONGO_URI=$MONGO_URI --FOREIGN_SERVICE_OPINION=$FOREIGN_SERVICE_OPINION --PORT=$PORT_SURVEY_MOCHA --ENVIRONMENT=test $DIST_PATH_SURVEY


#build-and-push-container-stage:
#  stage: build-and-push-container-stage
#  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
#  before_script:
#    - export SERVICE_NAME=survey
#    - export SERVICE_NAME2=opinion
#  script:
#
#  dependencies:
#    - compile-and-test-stage

#testing_testing:
#  stage: test
#  dependencies:
#    - npm
#  script:
#    - npm run testDot