variables:
  MONGODB_VERSION: "4.2"
  NODEJS_VERSION: "12.18.2-slim"
  #CI_AWS_ECS_CLUSTER: wp-ms-surveys-cluster
  #CI_AWS_ECS_SERVICE: wp-ms-surveys-survey-service
  #CI_AWS_ECS_TASK_DEFINITION: wp-ms-surveys-survey-task
  MONGO_URI: mongodb://mongo:27017/wp-ms-surveys
  FOREIGN_SERVICE_OPINION: http://opinionservice:8081/opinion
  FOREIGN_SERVICE_SURVEY:  http://opinionservice:8081/survey
  PORT_SURVEY: 8080
  PORT_OPINION: 8081
  ENVIRONMENT: test
  DIST_PATH_SURVEY: dist/Survey/Test
  DIST_PATH_OPINION: dist/Opinion/Test

image: NODEJS_VERSION

#This command is run before all the jobs
before_script:
  - npm install
  - npm install mocha -g --save
  - npm install source-map-support -g --save
  - npm install typescript -g --save
  - npm install ts-node -g --save

#include:
#  - template: AWS/Deploy-ECS.gitlab-ci.yml

stages:
  - build
  - test

services:
  - mongo:$MONGODB_VERSION

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm run build
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/
      - src/
      - dist/

testing_all:
  stage: test
  script:
    - mocha --MONGO_URI=$MONGO_URI --FOREIGN_SERVICE_OPINION=$FOREIGN_SERVICE_OPINION --PORT=$PORT_SURVEY --ENVIRONMENT=$ENVIRONMENT $DIST_PATH_SURVEY
    - mocha --MONGO_URI=$MONGO_URI --FOREIGN_SERVICE_SURVEY=$FOREIGN_SERVICE_SURVEY --PORT=$PORT_OPINION --ENVIRONMENT=$ENVIRONMENT $DIST_PATH_OPINION

#build-and-push-container-stage:
#  stage: build-and-push-container-stage
#  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
#  before_script:
#    - export SERVICE_NAME=survey
#    - export SERVICE_NAME2=opinion
#  script:
#
#  dependencies:
#    - compile-and-test-stage

#testing_testing:
#  stage: test
#  dependencies:
#    - npm
#  script:
#    - npm run testDot