variables:
  MONGODB_VERSION: "4.2"
  NODEJS_VERSION: "12.18.2-slim"
  #CI_AWS_ECS_CLUSTER: wp-ms-surveys-cluster
  #CI_AWS_ECS_SERVICE: wp-ms-surveys-survey-service
  #CI_AWS_ECS_TASK_DEFINITION: wp-ms-surveys-survey-task
  MONGO_URI_PM2: mongodb://localhost:27017/wp-ms-surveys_test
  MONGO_URI_MOCHA: mongodb://localhost:27017/wp-ms-surveys
  PORT_SURVEY_PM2: 8090
  PORT_SURVEY_MOCHA: 8080
  PORT_OPINION_PM2: 8091
  PORT_OPINION_MOCHA: 8081
  FOREIGN_SERVICE_OPINION_PM2: http://localhost:$PORT_OPINION_PM2/opinion
  FOREIGN_SERVICE_OPINION_MOCHA: http://localhost:$PORT_OPINION_MOCHA/opinion
  FOREIGN_SERVICE_SURVEY_PM2: http://localhost:$PORT_SURVEY_PM2/survey
  FOREIGN_SERVICE_SURVEY_MOCHA: http://localhost:$PORT_SURVEY_MOCHA/survey
  DIST_PATH_SURVEY: dist/Survey/Test
  DIST_PATH_OPINION: dist/Opinion/Test

image: node:$NODEJS_VERSION

#This command is run before all the jobs
before_script:
  - npm install
  - npm install mocha -g --save
  - npm install source-map-support -g --save
  - npm install typescript -g --save
  - npm install ts-node -g --save
  - npm install pm2 -g --save
  - docker login $DOCKER_REPOSITORY -u $REGISTRY_USER -p $REGISTRY_USER_PASSWORD

#include:
#  - template: AWS/Deploy-ECS.gitlab-ci.yml

stages:
  - build_local
  - test
  - build_and_push_docker

services:
  - mongo:$MONGODB_VERSION
  - docker:dind

cache:
  paths:
    - node_modules/

build_local:
  stage: build_local
  script:
    - npm run build
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/
      - src/
      - dist/

testing_survey:
  stage: test
  services:
    - mongo:latest
  dependencies:
    - build_local
  script:
    - pm2 start dist/Opinion/index.js --name "opinion" --source-map-support --reporter dot -- --MONGO_URI "$MONGO_URI_PM2" --FOREIGN_SERVICE_SURVEY "$FOREIGN_SERVICE_SURVEY_MOCHA" --PORT "$PORT_OPINION_PM2" --ENVIRONMENT "development"
    - mocha --MONGO_URI=$MONGO_URI_MOCHA --FOREIGN_SERVICE_OPINION=$FOREIGN_SERVICE_OPINION_PM2 --PORT=$PORT_SURVEY_MOCHA --ENVIRONMENT=test $DIST_PATH_SURVEY
    - pm2 kill

testing_opinion:
  stage: test
  services:
    - mongo:latest
  dependencies:
    - build_local
  script:
    - pm2 start dist/Survey/index.js --name "survey" --source-map-support --reporter dot -- --MONGO_URI "$MONGO_URI_PM2" --FOREIGN_SERVICE_OPINION "$FOREIGN_SERVICE_OPINION_MOCHA" --PORT "$PORT_SURVEY_PM2" --ENVIRONMENT "development"
    - mocha --MONGO_URI=$MONGO_URI_MOCHA --FOREIGN_SERVICE_SURVEY=$FOREIGN_SERVICE_SURVEY_PM2 --PORT=$PORT_OPINION_MOCHA --ENVIRONMENT=test $DIST_PATH_OPINION
    - pm2 kill

#building_mongo:
#  stage: build_and_push_docker
#  dependencies:
#    - build_local
#    - test
#  script:
#    - docker build -f src/Mongo/Dockerfile --no-cache -t "$REPO:$CI_BUILD_REF_NAME" .
#    - docker push $REPO:$CI_BUILD_REF_NAME

building_survey:
  stage: build_and_push_docker
  dependencies:
    - build_local
    - testing_survey
  script:
    # prebuild
    - echo Logging in to Amazon ECR...
    - aws --version
    - $(aws ecr get-login --region us-east-1 --no-include-email)
    - REPOSITORY_URI=697657657359.dkr.ecr.us-east-1.amazonaws.com/wp-ms-surveys-survey # uri of ECR
    - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    # build
    - docker build -f src/Survey/Dockerfile --no-cache -t "$REPO:$CI_BUILD_REF_NAME" .
    - docker push $REPO:$CI_BUILD_REF_NAME
    #post build
    - echo Build complete on `date`
    - echo Pusching the Docker images...
    - docker push $REPOSITORY_URI:latest # push to aws as latest tag
    - docker push $REPOSITORY_URI:$IMAGE_TAG # push to aws as regular tag
    - echo Writing image definitions file...
    - printf '[{"name":"wp-ms-surveys-survey-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json # create a file which helps the aws service to find the image
  artifacts:
    paths:
      - imagedefinitions.json

#building_opinion:
#  stage: build_and_push_docker
#  dependencies:
#    - build_local
#    - testing_opinion
#  script:
#    - docker build -f src/Survey/Dockerfile --no-cache -t "$REPO:$CI_BUILD_REF_NAME" .
#    - docker push $REPO:$CI_BUILD_REF_NAME