version: '3'

services:
  # -------------------------------------------------------
  # Databases
  # -------------------------------------------------------
  mongo:
    image: mongo:4.2
    container_name: mongo
    ports:
      - 27017:27017